version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Monitor C++ dependencies (manual configuration needed)
  # Since there's no native C++ package manager support,
  # we can monitor submodules if we add any
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "submodules"
    commit-message:
      prefix: "chore"
      include: "scope"
