codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 75%
        threshold: 5%

ignore:
  - "build"
  - "tests"
  - "*_autogen"
  - "**/*_test.cpp"
  - "**/*_test.hpp"
  - "src/gui/ui"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
